name: Setup
description: Set up the environment

inputs:
  node-version:
    description: The Node.js version to install
    required: false
    default: '18'
  package:
    description: Only install dependencies for the given package
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest
    - name: Install Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: https://registry.npmjs.org/
        cache: "pnpm"
    - name: Install depdendencies (all)
      if: ${{ inputs.package == '' }}
      shell: bash
      run: pnpm install
    - name: Install depdendencies (${{ inputs.package }})
      if: ${{ inputs.package != '' }}
      shell: bash
      run: pnpm --filter ${{ inputs.package }} install
