name: publish

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: publish
  cancel-in-progress: true

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: pnpm --filter docs build
      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs/build/

  build-vality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: pnpm --filter src build
      - run: cp ./README.md ./src/README.md
      - run: ls -la
      - uses: actions/upload-artifact@v3
        with:
          name: publish-vality
          path: |
            ./src/dist/
            ./src/package.json
            ./src/yarn.lock
            ./src/LICENSE.md
            ./src/README.md

  deploy-docs:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build-docs
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v1
        id: deployment

  publish-vality:
    name: Publish to NPM
    needs: build-vality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: publish-vality
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
