name: test and lint

on:
  push:

jobs:
  jest:
    name: jest (Node ${{ matrix.node-version}})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16, 18]

    steps:
      - uses: actions/checkout@v3
      - name: Install Node ${{ matrix.node-version }}
        uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run jest
        run: pnpm test

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Run eslint
        run: pnpm lint

  status:
    needs: ["jest", "lint"]
    runs-on: ubuntu-latest
    steps:
      - uses: LouisBrunner/checks-action@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          conclusion: ${{ job.status }}
